# Generated by Django 2.0.2 on 2018-02-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
