# Generated by Django 2.0.2 on 2018-03-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180228_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumLogo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='albumTitle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
